title:             Wesh Jyan Oasuuui
email:             oasuuui@gmail.com
description:       Blog@Github nih
author:            Oasuuui
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://oasuuui.github.io"

# Social Profiles
twitter_username:  empty
github_username:   oasuuui
facebook_username: empty

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-minimal